@startuml aggiornamento_firmware_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm
actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC3 - Aggiornamento del firmware Gateway" as UC3
  usecase "UC3.1 - Selezione firmware" as UC3_1
  usecase "UC78 - Selezione Gateway" as UC78
}

tenant_adm -- UC3
p_gway -- UC3

UC3 ..> UC78 : <<include>>
UC3 ..> UC3_1 : <<include>>

@enduml