@startuml creazione_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm
actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC9 - Creazione Tenant" as UC9
  usecase "UC9.2 - Creazione Utente del Tenant" as UC9_2
  usecase "UC9.1 - Inserimento dati anagrafici Tenant" as UC9_1
  usecase "UC9.2.1 - Inserimento nome Utente" as UC9_2_1
  usecase "UC44 - Impostazione mail" as UC44
  usecase "UC45 - Impostazione password" as UC45
  usecase "UC79 - Selezione permessi Utente" as UC79
  usecase "UC26 - Errore interno creazione Tenant" as UC26
}

sys_adm -- UC9
tenant_adm -- UC9

UC9 ..> UC9_1 : <<include>>
UC9 ..> UC9_2 : <<include>>
UC9_2 ..> UC9_2_1 : <<include>>
UC9_2 ..> UC79 : <<include>>
UC9_2 ..> UC44 : <<include>>
UC9_2 ..> UC45 : <<include>>
UC26 ..> UC9 : <<extend>>
note on link
  Extension Point: ErroreInternoCreazione
  Condition: Si verifica un errore interno durante la procedura di creazione del Tenant
end note

@enduml