@startuml creazione_utente_amministratore_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC10 - Creazione Utente Amministratore Tenant" as UC10
  usecase "UC44 - Impostazione mail" as UC44
  usecase "UC45 - Impostazione password" as UC45
}

sys_adm -- UC10

UC10 ..> UC44 : <<include>>
UC10 ..> UC45 : <<include>>

@enduml