@startuml eliminazione_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC14.1 - Conferma eliminazione Tenant" as UC14_1
  usecase "UC14 - Eliminazione Tenant" as UC14
}

sys_adm -- UC14

UC14 ..> UC14_1 : <<include>>

@enduml