@startuml err_intervallo_temporale_invalido
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Client API" as api_client

rectangle "Sistema Cloud" {
  usecase "UC27 - Errore intervallo Temporale Invalido" as UC27
}

api_client -- UC27


@enduml