@startuml err_autenticazione_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC17 - Errore Autenticazione Gateway" as UC17
}

p_gway -- UC17


@enduml