@startuml err_range_invalido
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC33 - Errore range invalido" as UC33
}

tenant_adm -- UC33


@enduml