@startuml err_dati_non_disponibili
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC23 - Errore dati non disponibili" as UC23
}

tenant_usr -- UC23


@enduml