@startuml err_dati_autenticazione_invalidi
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Client API" as api_client
actor "Auth Server" as auth_server

rectangle "Sistema Cloud" {
  usecase "UC22 - Errore dati di autenticazione non validi" as UC22
}

api_client -- UC22
auth_server -- UC22


@enduml