@startuml err_interno_creazione_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC26 - Errore interno creazione Tenant" as UC26
}

sys_adm -- UC26


@enduml