@startuml err_id_gateway_invalido
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Client API" as api_client

rectangle "Sistema Cloud" {
  usecase "UC24 - Errore ID Gateway invalido" as UC24
}

api_client -- UC24


@enduml