@startuml err_deploy_gateway_simulato
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente del Simulatore" as sim_usr

rectangle "Simulatore Gateway" {
  usecase "UCS11 - Errore Deploy Gateway simulato" as UCS11
}

sim_usr -- UCS11


@enduml