@startuml err_mail_gia_registrata
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Autenticato" as authd_usr

rectangle "Sistema Cloud" {
  usecase "UC28 - Errore mail duplicata" as UC28
}

authd_usr -- UC28


@enduml