@startuml err_config_frequenza_fuori_range
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Sistema Cloud" as cloud

rectangle "Simulatore Gateway" {
  usecase "UCS9 - Errore configurazione frequenza invio dati fuori range ammesso" as UCS9
}

cloud -- UCS9


@enduml