@startuml err_campi_diversi
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Autenticato" as authd_usr
actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC20 - Errore campi non corrispondenti" as UC20
}

authd_usr -- UC20
non_authd_usr -- UC20


@enduml