@startuml err_password_invalida
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Autenticato" as authd_usr
actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC32 - Errore password non valida" as UC32
}

authd_usr -- UC32
non_authd_usr -- UC32


@enduml