@startuml err_otp_errato
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC31 - Errore OTP errato" as UC31
}

non_authd_usr -- UC31


@enduml