@startuml err_range_invalido_simulazione
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente del Simulatore" as sim_usr

rectangle "Simulatore Gateway" {
  usecase "UCS12 - Errore range invalido del sensore simulato" as UCS12
}

sim_usr -- UCS12


@enduml