@startuml filtraggio_dati
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC39 - Filtraggio dati" as UC39
  usecase "UC40 - Filtraggio dati per Gateway" as UC40
  usecase "UC41 - Filtraggio dati per intervallo temporale" as UC41
  usecase "UC42 - Filtraggio dati per sensore" as UC42
  usecase "UC40.1 - Filtraggio dati per singolo Gateway" as UC40_1
  usecase "UC42.1 - Filtraggio dati per singolo sensore" as UC42_1
}

tenant_usr -- UC39

UC40 ..> UC40_1 : <<include>>
UC42 ..> UC42_1 : <<include>>
UC39 <|-- UC40
UC39 <|-- UC41
UC39 <|-- UC42

@enduml