@startuml impostazione_password
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Autenticato" as authd_usr
actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC45.2 - Conferma nuova password" as UC45_2
  usecase "UC45 - Impostazione password" as UC45
  usecase "UC45.1 - Inserimento nuova password" as UC45_1
  usecase "UC20 - Errore campi non corrispondenti" as UC20
  usecase "UC32 - Errore password non valida" as UC32
}

authd_usr -- UC45
non_authd_usr -- UC45

UC45 ..> UC45_1 : <<include>>
UC45 ..> UC45_2 : <<include>>
UC20 ..> UC45_2 : <<extend>>
note on link
  Extension Point: PasswordDiverse
  Condition: La stringa inserita nel campo di conferma non corrisponde a quella inserita in precedenza
end note
UC32 ..> UC45_1 : <<extend>>
note on link
  Extension Point: PasswordInvalida
  Condition: La password inserita non rispetta le policy di sicurezza del Sistema (es. lunghezza minima, presenza di caratteri speciali)
end note

@enduml