@startuml impostazione_mail
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Autenticato" as authd_usr
actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC44.2 - Conferma mail" as UC44_2
  usecase "UC44 - Impostazione mail" as UC44
  usecase "UC44.1 - Inserimento mail" as UC44_1
  usecase "UC20 - Errore campi non corrispondenti" as UC20
  usecase "UC29 - Errore mail non valida" as UC29
  usecase "UC28 - Errore mail duplicata" as UC28
}

authd_usr -- UC44
non_authd_usr -- UC44

UC44 ..> UC44_1 : <<include>>
UC44 ..> UC44_2 : <<include>>
UC20 ..> UC44_2 : <<extend>>
note on link
  Extension Point: FallimentoValidazione
  Condition: L’Attore inserisce due valori diversi nei due campi
end note
UC29 ..> UC44_1 : <<extend>>
note on link
  Extension Point: MailInvalida
  Condition: L’Attore inserisce una mail non valida
end note
UC28 ..> UC44_1 : <<extend>>
note on link
  Extension Point: MailInvalida
  Condition: L’Attore inserisce una mail già associata ad un altro account
end note

@enduml