@startuml ins_mail
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC46 - Inserimento mail" as UC46
}

non_authd_usr -- UC46


@enduml