@startuml ins_otp
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC47 - Inserimento OTP" as UC47
  usecase "UC31 - Errore OTP errato" as UC31
}

non_authd_usr -- UC47

UC31 ..> UC47 : <<extend>>
note on link
  Extension Point: OtpErrato
  Condition: L'OTP inserito non viene riconosciuto come valido dal Sistema
end note

@enduml