@startuml invio_dati_crittografati_cloud
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Not Provisioned Gateway" as np_gway
actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC49.1 - Instaurazione connessione sicura" as UC49_1
  usecase "UC49 - Invio dati crittografati al Cloud" as UC49
  usecase "UC17 - Errore Autenticazione Gateway" as UC17
}

np_gway -- UC49
p_gway -- UC49

UC49 ..> UC49_1 : <<include>>
UC17 ..> UC49_1 : <<extend>>
note on link
  Extension Point: CertificatoRifiutato
  Condition: Il Cloud rifiuta il certificato del Gateway
end note

@enduml