@startuml lista_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC50 - Visualizzazione lista Gateway" as UC50
  usecase "UC50.1 - Visualizzazione singolo Gateway" as UC50_1
  usecase "UC107 - Visualizzazione nome Gateway" as UC107
  usecase "UC110 - Visualizzazione stato Gateway" as UC110
}

tenant_usr -- UC50

UC50 ..> UC50_1 : <<include>>
UC50_1 ..> UC107 : <<include>>
UC50_1 ..> UC110 : <<include>>

@enduml