@startuml login
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC51.1 - Inserimento password" as UC51_1
  usecase "UC51 - Login" as UC51
  usecase "UC52 - Login 2FA" as UC52
  usecase "UC46 - Inserimento mail" as UC46
  usecase "UC47 - Inserimento OTP" as UC47
  usecase "UC21 - Errore credenziali errate" as UC21
}

non_authd_usr -- UC51

UC51 ..> UC46 : <<include>>
UC51 ..> UC51_1 : <<include>>
UC52 ..> UC47 : <<include>>
UC21 ..> UC51 : <<extend>>
note on link
  Extension Point: PreLogin
  Condition: L'Attore inserisce credenziali errate
end note
UC51 <|-- UC52

@enduml