@startuml logout
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Autenticato" as authd_usr

rectangle "Sistema Cloud" {
  usecase "UC53 - Logout" as UC53
}

authd_usr -- UC53


@enduml