@startuml modifica_impostazioni_2fa
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC55 - Modifica impostazioni 2FA login dashboard" as UC55
}

tenant_adm -- UC55


@enduml