@startuml modifica_impostazioni_notifica_alert_dashboard
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC1 - Abilitazione notifica alert via dashboard" as UC1
  usecase "UC11 - Disabilitazione notifica alert via dashboard" as UC11
  usecase "UC57 - Modifica impostazioni notifica alert via dashboard" as UC57
}

tenant_usr -- UC57

UC57 <|-- UC1
UC57 <|-- UC11

@enduml