@startuml modifica_range_sensore
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm
actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC69 - Modifica range alert sensore specifico" as UC69
  usecase "UC80 - Selezione range numerico misurazioni" as UC80
  usecase "UC33 - Errore range invalido" as UC33
}

tenant_adm -- UC69
p_gway -- UC69

UC69 ..> UC80 : <<include>>
UC33 ..> UC69 : <<extend>>
note on link
  Extension Point: RangeInvalido
  Condition: Il range inserito non è valido (min > max)
end note

@enduml