@startuml modifica_password_utente
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC66 - Modifica password Utente del Tenant" as UC66
  usecase "UC45 - Impostazione password" as UC45
}

tenant_adm -- UC66

UC66 ..> UC45 : <<include>>

@enduml