@startuml modifica_stato_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm
actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC70 - Modifica stato del Gateway" as UC70
  usecase "UC70.1 - Selezione stato del Gateway" as UC70_1
}

tenant_adm -- UC70
p_gway -- UC70

UC70 ..> UC70_1 : <<include>>

@enduml