@startuml onboarding_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Not Provisioned Gateway" as np_gway

rectangle "Sistema Cloud" {
  usecase "UC72 - Provisioning Gateway - Onboarding" as UC72
  usecase "UC18 - Errore autenticazione Gateway di fabbrica" as UC18
}

np_gway -- UC72

UC18 ..> UC72 : <<extend>>
note on link
  Extension Point: CredenzialiNonRiconosciute
  Condition: Le credenziali fornite non corrispondono a quelle registrate
end note

@enduml