@startuml recupero_password
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Utente Non Autenticato" as non_authd_usr

rectangle "Sistema Cloud" {
  usecase "UC73 - Recupero password" as UC73
  usecase "UC46 - Inserimento mail" as UC46
  usecase "UC16 - Errore account non esistente" as UC16
}

non_authd_usr -- UC73

UC73 ..> UC46 : <<include>>
UC16 ..> UC73 : <<extend>>
note on link
  Extension Point: UtenteInesistente
  Condition: L'Attore inserisce una mail non registrata
end note

@enduml