@startuml registrazione_associazione_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC74.1 - Inserimento credenziali di fabbrica Gateway" as UC74_1
  usecase "UC74 - Provisioning Gateway - Registrazione e associazione Tenant" as UC74
  usecase "UC82 - Selezione Tenant" as UC82
}

sys_adm -- UC74

UC74 ..> UC82 : <<include>>
UC74 ..> UC74_1 : <<include>>

@enduml