@startuml riattivazione_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC75 - Riattivazione Tenant" as UC75
  usecase "UC82 - Selezione Tenant" as UC82
}

sys_adm -- UC75

UC75 ..> UC82 : <<include>>

@enduml