@startuml richiesta_dati_streaming
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Client API" as api_client
actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC77 - Richiesta dati Streaming" as UC77
  usecase "UC34 - Errore token autenticazione API invalido" as UC34
  usecase "UC24 - Errore ID Gateway invalido" as UC24
  usecase "UC25 - Errore ID Sensore invalido" as UC25
}

api_client -- UC77
p_gway -- UC77

UC34 ..> UC77 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: Il token fornito dall’Utente non è valido
end note
UC24 ..> UC77 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: ID Gateway invalido
end note
UC25 ..> UC77 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: ID sensore invalido
end note

@enduml