@startuml richiesta_dati_on_demand
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Client API" as api_client

rectangle "Sistema Cloud" {
  usecase "UC76 - Richiesta dati On-Demand" as UC76
  usecase "UC34 - Errore token autenticazione API invalido" as UC34
  usecase "UC24 - Errore ID Gateway invalido" as UC24
  usecase "UC25 - Errore ID Sensore invalido" as UC25
  usecase "UC27 - Errore intervallo Temporale Invalido" as UC27
}

api_client -- UC76

UC34 ..> UC76 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: Il token fornito dall’Utente non è valido
end note
UC24 ..> UC76 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: ID Gateway invalido
end note
UC25 ..> UC76 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: ID sensore invalido
end note
UC27 ..> UC76 : <<extend>>
note on link
  Extension Point: DatiNonValidi
  Condition: Intervallo temporale malformato
end note

@enduml