@startuml selezione_permessi_utente
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC79 - Selezione permessi Utente" as UC79
}

tenant_adm -- UC79


@enduml