@startuml selezione_utente_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC84 - Selezione Utente Tenant" as UC84
}

tenant_adm -- UC84


@enduml