@startuml selezione_specifico_sensore
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC81 - Selezione specifico sensore" as UC81
}

tenant_adm -- UC81


@enduml