@startuml sospensione_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC86 - Sospensione Tenant" as UC86
  usecase "UC82 - Selezione Tenant" as UC82
}

sys_adm -- UC86

UC86 ..> UC82 : <<include>>

@enduml