@startuml visualizzazione_id_sensore
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC100 - Visualizzazione ID sensore" as UC100
}

tenant_usr -- UC100


@enduml