@startuml visualizzazione_log_audit_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm
actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC105 - Visualizzazione log di Audit del Tenant" as UC105
  usecase "UC105.1.3 - Visualizzazione operazione log entry" as UC105_1_3
  usecase "UC105.1 - Visualizzazione singola entry log di Audit del Tenant" as UC105_1
  usecase "UC105.1.1 - Visualizzazione timestamp log entry" as UC105_1_1
  usecase "UC105.1.2 - Visualizzazione Utente log entry" as UC105_1_2
}

sys_adm -- UC105
tenant_adm -- UC105

UC105 ..> UC105_1 : <<include>>
UC105_1 ..> UC105_1_1 : <<include>>
UC105_1 ..> UC105_1_2 : <<include>>
UC105_1 ..> UC105_1_3 : <<include>>

@enduml