@startuml visualizzazione_timestamp_dato_irregolare
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC113 - Visualizzazione timestamp registrazione dato irregolare" as UC113
}

tenant_usr -- UC113


@enduml