@startuml visualizzazione_dettagli_alert_gateway_irraggiungibile
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC92 - Visualizzazione dettagli alert Gateway non raggiungibile" as UC92
  usecase "UC107 - Visualizzazione nome Gateway" as UC107
  usecase "UC115 - Visualizzazione timestamp ultimo invio dati Gateway" as UC115
}

tenant_usr -- UC92

UC92 ..> UC107 : <<include>>
UC92 ..> UC115 : <<include>>

@enduml