@startuml visualizzazione_lista_api
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC102 - Visualizzazione lista credenziali API del Tenant" as UC102
  usecase "UC102.1.1 - Visualizzazione nome descrittivo credenziali API" as UC102_1_1
  usecase "UC102.1 - Visualizzazione singole credenziali API del Tenant" as UC102_1
  usecase "UC102.1.2 - Visualizzazione timestamp creazione credenziali API" as UC102_1_2
  usecase "UC89 - Visualizzazione Client ID" as UC89
  usecase "UC106 - Visualizzazione mail dell’Utente" as UC106
}

tenant_adm -- UC102

UC102 ..> UC102_1 : <<include>>
UC102_1 ..> UC102_1_1 : <<include>>
UC102_1 ..> UC89 : <<include>>
UC102_1 ..> UC106 : <<include>>
UC102_1 ..> UC102_1_2 : <<include>>

@enduml