@startuml visualizzazione_valore_dato_registrato
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC116 - Visualizzazione valore del dato registrato" as UC116
}

tenant_usr -- UC116


@enduml