@startuml visualizzazione_timestamp_emissione_alert
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC114 - Visualizzazione timestamp emissione alert" as UC114
}

tenant_usr -- UC114


@enduml