@startuml visualizzazione_storico_alert
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC112.1.2 - Visualizzazione hardware interessato" as UC112_1_2
  usecase "UC112.1 - Visualizzazione singolo alert" as UC112_1
  usecase "UC112 - Visualizzazione storico alert" as UC112
  usecase "UC112.1.1 - Visualizzazione tipo di alert" as UC112_1_1
  usecase "UC114 - Visualizzazione timestamp emissione alert" as UC114
}

tenant_usr -- UC112

UC112_1 ..> UC114 : <<include>>
UC112_1 ..> UC112_1_1 : <<include>>
UC112_1 ..> UC112_1_2 : <<include>>
UC112 ..> UC112_1 : <<include>>

@enduml