@startuml visualizzazione_client_id
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant Admin" as tenant_adm

rectangle "Sistema Cloud" {
  usecase "UC89 - Visualizzazione Client ID" as UC89
}

tenant_adm -- UC89


@enduml