@startuml visualizzazione_dettagli_gateway
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC94 - Visualizzazione dettagli Gateway" as UC94
  usecase "UC94.1 - Visualizzazione lista sensori" as UC94_1
  usecase "UC94.1.1 - Visualizzazione singolo sensore" as UC94_1_1
  usecase "UC94.1.1.1 - Visualizzazione timestamp ultimo invio dati sensore" as UC94_1_1_1
  usecase "UC100 - Visualizzazione ID sensore" as UC100
  usecase "UC107 - Visualizzazione nome Gateway" as UC107
  usecase "UC110 - Visualizzazione stato Gateway" as UC110
  usecase "UC115 - Visualizzazione timestamp ultimo invio dati Gateway" as UC115
}

tenant_usr -- UC94

UC94 ..> UC107 : <<include>>
UC94 ..> UC110 : <<include>>
UC94 ..> UC115 : <<include>>
UC94 ..> UC94_1 : <<include>>
UC94_1 ..> UC94_1_1 : <<include>>
UC94_1_1 ..> UC100 : <<include>>
UC94_1_1 ..> UC94_1_1_1 : <<include>>

@enduml