@startuml visualizzazione_nome_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC108 - Visualizzazione nome Tenant" as UC108
}

sys_adm -- UC108


@enduml