@startuml visualizzazione_dettagli_tenant
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Amministratore di Sistema" as sys_adm

rectangle "Sistema Cloud" {
  usecase "UC96 - Visualizzazione dettagli Tenant" as UC96
  usecase "UC96.1 - Visualizzazione intervallo minimo di sospensione pre-eliminazione" as UC96_1
  usecase "UC101 - Visualizzazione ID Tenant" as UC101
  usecase "UC108 - Visualizzazione nome Tenant" as UC108
  usecase "UC111 - Visualizzazione stato Tenant" as UC111
}

sys_adm -- UC96

UC96 ..> UC108 : <<include>>
UC96 ..> UC111 : <<include>>
UC96 ..> UC101 : <<include>>
UC96 ..> UC96_1 : <<include>>

@enduml