@startuml visualizzazione_dati_stream
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr
actor "Provisioned Gateway" as p_gway

rectangle "Sistema Cloud" {
  usecase "UC91 - Visualizzazione dati Stream" as UC91
  usecase "UC91.2 - Visualizzazione grafico dati Stream" as UC91_2
  usecase "UC91.1 - Visualizzazione tabellare dati Stream" as UC91_1
  usecase "UC23 - Errore dati non disponibili" as UC23
}

tenant_usr -- UC91
p_gway -- UC91

UC91 ..> UC91_1 : <<include>>
UC91 ..> UC91_2 : <<include>>
UC23 ..> UC91 : <<extend>>
note on link
  Extension Point: NessunDato
  Condition: Non ci sono dati da visualizzare
end note

@enduml