@startuml visualizzazione_range_accettato
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC109 - Visualizzazione range accettato" as UC109
}

tenant_usr -- UC109


@enduml