@startuml visualizzazione_dettagli_alert_sensore_fuori_range
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FEFECE
  BorderColor #A80036
}

actor "Tenant User" as tenant_usr

rectangle "Sistema Cloud" {
  usecase "UC93 - Visualizzazione dettagli alert sensore fuori range" as UC93
  usecase "UC100 - Visualizzazione ID sensore" as UC100
  usecase "UC109 - Visualizzazione range accettato" as UC109
  usecase "UC113 - Visualizzazione timestamp registrazione dato irregolare" as UC113
  usecase "UC116 - Visualizzazione valore del dato registrato" as UC116
}

tenant_usr -- UC93

UC93 ..> UC100 : <<include>>
UC93 ..> UC116 : <<include>>
UC93 ..> UC113 : <<include>>
UC93 ..> UC109 : <<include>>

@enduml