#let terms = (
  "docs-as-code": "Approccio utilizzato per la gestione documentale attraverso codice",
  "commit": "Operazione con cui si registrano modifiche in un sistema di controllo versione (come Git). Deve essere atomico, cioè riguardare un singolo cambiamento coerente",
  "linee guida": "Indicazioni operative e stilistiche che regolano la redazione, il formato e il contenuto dei documenti del progetto",
  "pull-request": "Richiesta di integrazione di modifiche da un branch secondario al branch principale di un repository. Permette la revisione del codice prima dell’unione definitiva",
  "PR": "Abbreviazione di pull request. Utilizzata comunemente per indicare la richiesta di revisione o integrazione nel flusso di lavoro Git",
  "branch": "Linea di sviluppo indipendente all’interno di un repository Git, utilizzata per lavorare su nuove funzionalità o correzioni senza influenzare il codice principale",
  "main": "Branch principale di un repository Git, che contiene la versione stabile e ufficiale del progetto",
  "editor": "Membro del gruppo incaricato della redazione o modifica di un documento all’interno del progetto",
  "template": "Struttura predefinita utilizzata come modello per la redazione uniforme dei documenti del progetto",
  "versionamento": "Processo di gestione e numerazione progressiva delle versioni dei documenti o del codice per garantire tracciabilità e ordine",
  "merge": "Operazione con cui si uniscono le modifiche di un branch secondario nel branch principale, dopo approvazione e revisione",
  "automazione": "Procedura o insieme di strumenti che consentono l’esecuzione automatica di attività ripetitive, come la pubblicazione di documenti o la build del progetto",
  "Scrum Master": "Membro del team con il compito di facilitare l’applicazione del metodo Scrum, rimuovere ostacoli e promuovere buone pratiche di lavoro collaborativo",
  "Scrum": "Framework di sviluppo Agile basato su iterazioni (sprint) e ruoli definiti, volto a migliorare la collaborazione e la gestione del lavoro di gruppo",
  "Sprint Planning": "Fase iniziale di ogni sprint in cui il team definisce gli obiettivi e pianifica le attività da completare",
  "sprint": "Periodo di tempo prefissato, tipicamente di una o due settimane, durante il quale il team di sviluppo lavora su un insieme definito di attività",
  "task": "Unità di lavoro specifica e delimitata, generalmente associata a una singola attività o obiettivo da completare",
  "repository": "Archivio centralizzato che contiene il codice sorgente, la documentazione e la cronologia delle versioni di un progetto, gestito tramite sistemi come Git",
  "GitHub Projects": "Strumento integrato in GitHub per la gestione dei progetti, che consente di pianificare, assegnare e monitorare task in modo collaborativo tramite board e workflow personalizzabili",
  "GitHub": "Piattaforma di hosting per repository Git che consente la collaborazione, la revisione del codice e la gestione dei progetti tramite pull request e issue tracking",
  "Discord": "Piattaforma di comunicazione online che permette chat vocali, testuali e video, utilizzata per coordinare le attività e tenere riunioni virtuali del gruppo",
  "Git": "Sistema di controllo versione distribuito che consente di tracciare le modifiche al codice sorgente e lavorare in modo collaborativo su progetti software",
  "Way of Working": "Documento o insieme di pratiche che descrive le modalità operative, gli strumenti e le regole adottate dal team per collaborare in modo efficace e coerente",
  "template Typst": "Modello predefinito scritto in linguaggio Typst, utilizzato per standardizzare la struttura grafica e formale dei documenti del gruppo",
  "Typst": "Linguaggio di composizione testuale per la creazione di documenti strutturati, caratterizzato da una sintassi chiara e moderna, alternativo a LaTeX e adatto all’automazione della documentazione",
  "version control": "Sistema che consente di registrare, monitorare e gestire le modifiche al codice sorgente o ai documenti di progetto nel tempo, garantendo tracciabilità e collaborazione",
  "Agile": "Insieme di principi e pratiche di sviluppo software basate su iterazioni brevi, feedback continui e collaborazione costante tra i membri del team",
  "cowork": "Sessione di lavoro condiviso tra i membri del gruppo, svolta in contemporanea per favorire la collaborazione e la produttività",
  "foglio elettronico": "Documento digitale strutturato in celle che consente di organizzare, calcolare e visualizzare dati in forma tabellare, ad esempio tramite software come Google Sheets",
  "Google Docs": "Piattaforma cloud per la creazione, modifica e condivisione collaborativa di documenti testuali in tempo reale",
  "appalto": "Termine usato in senso figurato per indicare l’assegnazione di un capitolato a un gruppo, a seguito della selezione da parte dell’azienda proponente",
  "audit": "Attività di analisi e verifica sistematica su codice, processi o documentazione per valutarne qualità e conformità",
)