#let terms = (
  // A
  "Advertising": "Modalità operativa del protocollo BLE in cui il dispositivo periferico trasmette periodicamente pacchetti di dati senza necessità di connessione, ottimizzando il consumo energetico",
  "Agile": "Insieme di principi e pratiche di sviluppo software basate su iterazioni brevi, feedback continui e collaborazione costante tra i membri del team",
  "ACK": "Abbreviazione di Acknowledgement, in ambito informatico, è il simbolo che identifica un segnale di riconoscimento emesso in risposta alla ricezione di un'informazione completa",
  "Angular": "Framework TypeScript per lo sviluppo di applicazioni web Single Page Application, sviluppato da Google",
  "API Gateway": "Componente architetturale che funge da punto di accesso centralizzato per le API, gestendo autenticazione, autorizzazione e rate limiting delle richieste",
  "API Token": "Credenziale digitale che autorizza un client a utilizzare un'API, permettendo l'autenticazione e il controllo dell'accesso alle risorse esposte",
  "Apache Kafka": "Piattaforma open source di streaming distribuito per la pubblicazione, sottoscrizione e elaborazione di flussi di dati in tempo reale",
  "artifact": "File o insieme di file generato automaticamente da un processo di build o verifica (es. il PDF compilato da una automazione), pronto per essere controllato o distribuito",
  "asset": "Risorsa digitale statica (es. immagini, diagrammi, loghi) inclusa nella documentazione o nel software",
  "appalto": "Termine usato in senso figurato per indicare l'assegnazione di un capitolato a un gruppo, a seguito della selezione da parte dell'azienda proponente",
  "Auth0": "Servizio cloud di autenticazione e autorizzazione che gestisce identità e accesso per applicazioni, fornendo SSO e supporto per molteplici provider di identità",
  "audit": "Attività di analisi e verifica sistematica su codice, processi o documentazione per valutarne qualità e conformità",
  "automazione": "Procedura o insieme di strumenti che consentono l'esecuzione automatica di attività ripetitive, come la pubblicazione di documenti o la build del progetto",
  // B
  "Backlog": "Elenco ordinato di attività, requisiti e work items da completare durante il ciclo di vita del progetto",
  "Backend": "Componente del sistema che gestisce l'elaborazione dei dati, la logica di business e la persistenza, separato dall'interfaccia utente",
  "baseline": "Versione stabile e approvata di un prodotto (documento o software) che funge da punto di partenza ufficiale per lo sviluppo successivo",
  "branch": "Linea di sviluppo indipendente all'interno di un repository Git, utilizzata per lavorare su nuove funzionalità o correzioni senza influenzare il codice principale",
  "BLE": "Acronimo di Bluetooth Low Energy, è una tecnologia wireless personal area network progettata e commercializzata per nuove applicazioni in vari settori fornendo un consumo energetico e un costo notevolmente basso",
  "BYOK": "Acronimo di Bring Your Own Key, modello di cifratura in cui le chiavi crittografiche sono gestite esclusivamente dal cliente e mai esposte all'infrastruttura del provider",
  // C
  "Capitolato": "Documento formale che descrive i requisiti, le specifiche tecniche e le condizioni di un progetto software da realizzare",
  "changelog": "Registro cronologico delle modifiche apportate al progetto, solitamente associato alle versioni rilasciate, per tracciare l'evoluzione del prodotto",
  "CI/CD": "Insieme di pratiche e strumenti per integrazione continua e distribuzione continua, a supporto di build, test e release automatici",
  "Cloud-native": "Paradigma di sviluppo che sfrutta servizi e architetture progettate specificamente per ambienti cloud scalabili",
  "CMMI": "Approccio al miglioramento dei processi che fornisce alle organizzazioni gli elementi essenziali per un efficace miglioramento dei processi",
  "Code Review": "Processo di verifica sistematica del codice sorgente da parte di altri sviluppatori per garantire qualità e conformità",
  "Cold Start": "Latenza iniziale che si verifica in architetture serverless quando una funzione inattiva deve essere istanziata prima di poter gestire una richiesta",
  "commit": "Operazione con cui si registrano modifiche in un sistema di controllo versione (come Git). Deve essere atomico, cioè riguardare un singolo cambiamento coerente",
  "Conventional Commits": "Standard strutturato per la formattazione dei messaggi di commit che garantisce leggibilità e tracciabilità della cronologia",
  "convention over configuration": "Principio di progettazione secondo cui scelte predefinite e convenzioni riducono la necessità di configurazioni esplicite, semplificando lo sviluppo",
  "cowork": "Sessione di lavoro condiviso tra i membri del gruppo, svolta in contemporanea per favorire la collaborazione e la produttività",
  // D
  "Dashboard": "Interfaccia grafica che visualizza in forma sintetica dati e metriche del sistema, permettendo monitoraggio e amministrazione",
  "Defense in Depth": "Strategia di sicurezza che applica molteplici livelli di protezione in parallelo, in modo che il compromesso di uno strato non comprometta l'intero sistema",
  "deliverable": "Prodotto intermedio o finale (documento, artefatto, versione) consegnato come risultato di attività pianificate",
  "Deploy": "Processo di distribuzione e installazione del software in un ambiente di test o produzione",
  "Diario di Bordo": "Documento di comunicazione con i professori dove il gruppo registra i progressi, le criticità e le considerazioni relative al progetto",
  "directory di documento": "Cartella dedicata alla raccolta e organizzazione dei file di un singolo documento all'interno della struttura del progetto",
  "Discord": "Piattaforma di comunicazione online che permette chat vocali, testuali e video, utilizzata per coordinare le attività e tenere riunioni virtuali del gruppo",
  "Docker Compose": "Strumento che facilita la definizione e l'esecuzione di applicazioni multi-contenitore Docker attraverso file di configurazione YAML",
  "Docker": "Tecnologia di containerizzazione che consente di confezionare applicazioni e le loro dipendenze in container portabili, facilitando deployment coerente su diverse piattaforme",
  "docs-as-code": "Approccio utilizzato per la gestione documentale attraverso codice",
  "DTO": "Acronimo di Data Transfer Object, è un design pattern usato per trasferire dati tra sottosistemi di un'applicazione software",
  // E
  "Edge Computing": "Paradigma architetturale che decentralizza l'elaborazione dei dati, eseguendo calcoli direttamente sui dispositivi periferici anziché inviarli al cloud",
  "End-to-End Encryption": "Protocollo di sicurezza dove i dati vengono cifrati all'origine e decifrati solo a destinazione, garantendo che nessun intermediario possa accedere ai dati in chiaro",
  "editor": "Membro del gruppo incaricato della redazione o modifica di un documento all'interno del progetto",
  // F
  "Feature Branch": "Ramo del repository temporaneo creato per lo sviluppo di una specifica funzionalità, da integrare successivamente nel ramo principale",
  "foglio elettronico": "Documento digitale strutturato in celle che consente di organizzare, calcolare e visualizzare dati utili al gruppo",
  "Frontend": "Componente del sistema che implementa l'interfaccia utente e interagisce con l'utente finale tramite browser",
  // G
  "GATT": "Acronimo di Generic Attribute Profile, architettura del protocollo BLE che definisce una struttura gerarchica per l'organizzazione dei dati in servizi e caratteristiche, utilizzata per connessioni stabili e bidirezionali",
  "Gateway": "Dispositivo fisico o software che funge da punto di accesso e intermediario per la comunicazione tra reti, sensori o sistemi diversi",
  "Gin": "Framework web leggero e ad alte prestazioni per il linguaggio Go, utilizzato per la costruzione di API REST",
  "GitHub Projects": "Strumento integrato in GitHub per la gestione dei progetti, che consente di pianificare, assegnare e monitorare task in modo collaborativo tramite board e workflow personalizzabili",
  "GitHub": "Piattaforma di hosting per repository Git che consente la collaborazione, la revisione del codice e la gestione dei progetti tramite pull request e issue tracking",
  "Git": "Sistema di controllo versione distribuito che consente di tracciare le modifiche al codice sorgente e lavorare in modo collaborativo su progetti software",
  "Go": "Linguaggio di programmazione compilato sviluppato da Google, progettato per semplicità, concorrenza e performance",
  "Golang": "Nome alternativo comunemente utilizzato per il linguaggio di programmazione Go, spesso usato per disambiguazione in contesti di ricerca",
  "Google Cloud Platform": "Suite di servizi cloud offerti da Google per computing, storage e deployment di applicazioni, utilizzata come infrastruttura di orchestrazione del progetto",
  "Google Docs": "Piattaforma cloud per la creazione, modifica e condivisione collaborativa di documenti testuali in tempo reale per raccogliere idee",
  "Gorm": "ORM per il linguaggio Go che fornisce un'interfaccia semplificata per interagire con database relazionali",
  "Grafana": "Piattaforma open source per la visualizzazione di metriche e la creazione di dashboard, integrata con Prometheus",
  "gRPC": "Framework open source per la comunicazione tra servizi distribuiti basato su Protocol Buffers, caratterizzato da bassa latenza e alta performance",
  "Groups": "Directory di primo livello situate all'interno della cartella principale docs/. Rappresentano le macro-categorie o le aree principali in cui è suddivisa la documentazione del progetto",
  // H
  "HTTPS": "Acronimo di HyperText Transfer Protocol Secure, protocollo di comunicazione sicura su Internet che utilizza TLS per cifrare i dati scambiati tra client e server",
  "Heartbeat": "Meccanismo di monitoraggio che invia segnali periodici per verificare che una connessione o un componente sia ancora attivo e funzionante",
  // I
  "Impersonificazione": "Funzionalità di sicurezza che consente a un utente amministratore di agire temporaneamente con i privilegi di un altro utente, con logging tracciato",
  "Integration Testing": "Metodologia di test che verifica le interazioni tra unità di codice integrate, assicurando che collaborino correttamente nel contesto di sistema",
  "IoT": "Acronimo di Internet of Things, ecosistema di dispositivi connessi a rete che raccolgono, elaborano e scambiano dati senza intervento umano diretto",
  "ISO 8601": "Standard internazionale per rappresentare date e orari in formato non ambiguo (es. yyyy-mm-dd)",
  "ISO/IEC 12207:1995": "Standard internazionale che definisce i processi del ciclo di vita del software (primari, di supporto, organizzativi) come riferimento metodologico",
  "issue": "Segnalazione, proposta o attività da gestita all'interno di un repository GitHub",
  // J
  "JavaScript": "Linguaggio di programmazione multi paradigma orientato agli eventi, fortemente utilizzato sia nella programmazione lato client web sia lato server.",
  "JetStream": "Estensione nativa di NATS che aggiunge persistenza dei dati e consegna garantita, permettendo l'archiviazione dei messaggi e il loro recupero successivo tramite modelli di consumo Push o Pull",
  "Jira": "Piattaforma software sviluppata da Atlassian, adottata dal gruppo come strumento principale per il Project Management e l'Issue Tracking. Viene utilizzata per pianificare le attività, tracciare i ticket (task o bug), gestire gli Sprint e monitorare lo stato di avanzamento del progetto in modo collaborativo.",
  "JSON": "Formato per lo scambio dati basato sul linguaggio di programmazione JavaScript",
  "JWT": "Acronimo di JSON Web Token, standard aperto per la creazione di token di accesso che consentono l'autenticazione e lo scambio sicuro di informazioni tra parti",
  // K
  "KeyCloak": "Piattaforma Open Source che permette di centralizzare l'autenticazione e l'autorizzazione per applicazioni e servizi moderni",
  "Kubernetes": "Piattaforma open source per l'orchestrazione di container che automatizza deployment, scaling e gestione di applicazioni containerizzate in ambienti distribuiti",
  // L
  "LaTeX": "Linguaggio utilizzato per la creazione di documenti scientifici e tecnici, basato su markup testuale e altamente personalizzabile",
  "linee guida": "Indicazioni operative e stilistiche che regolano la redazione, il formato e il contenuto dei documenti del progetto",
  "Living Document": "Documento in evoluzione continua, aggiornato man mano che processi e decisioni cambiano; mantiene storia e contesto nel tempo",
  // M
  "Message Broker": "Componente architetturale che gestisce l'ingestione, buffering e distribuzione di messaggi tra produttori e consumatori, disaccoppiando velocità di ricezione da quella di elaborazione",
  "Microservizi": "Architettura software che decompone un'applicazione in un insieme di servizi piccoli, indipendenti e focalizzati su specifiche funzionalità di business",
  "main": "Branch principale di un repository Git, che contiene la versione stabile e ufficiale del progetto",
  "Major": "Il primo numero nella notazione SemVer (X.Y.Z). Identifica il raggiungimento di una Baseline di progetto e viene incrementato esclusivamente in corrispondenza di rilasci formali.",
  "merge": "Operazione con cui si uniscono le modifiche di un branch secondario nel branch principale, dopo approvazione e revisione",
  "metadati": "Dati che descrivono altri dati o documenti (es. autore, versione, data, ambito, collocazione), usati per organizzazione e automazioni",
  "milestone": "Punto di controllo pianificato che segna un traguardo verificabile; scandisce avanzamento e rilasci",
  "Minor": "Il secondo numero nella notazione SemVer (X.Y.Z). Viene incrementato quando vengono aggiunte o rimosse sezioni significative al documento, mantenendo la compatibilità con le versioni precedenti (non stravolgono la struttura esistente).",
  "MongoDB": "Database NoSQL basato su documenti che consente la memorizzazione di dati non strutturati o semi-strutturati in formato JSON-like",
  "MQTT": "Protocollo di messaggistica leggero, standardizzato e basato sul modello publish/subscribe, ideale per dispositivi IoT e a risorse limitate",
  "Multi-tenancy": "Architettura in cui una singola istanza dell'applicazione serve molteplici tenant con segregazione completa dei dati e delle risorse",
  "mTLS": "Acronimo di mutual TLS, estensione del protocollo TLS in cui sia il client sia il server si autenticano reciprocamente tramite certificati digitali",
  "MVP": "Acronimo di Minimum Viable Product, è la versione basilare di un nuovo prodotto software che contiene solo le funzionalità essenziali atte a risolvere un problema chiave",
  // N
  "NestJS": "Framework Node.js basato su TypeScript per la costruzione di applicazioni server-side scalabili con architettura modulare e dependency injection",
  "NATS": "Sistema di messaggistica Open Source sviluppato da Cloud Native Computing Foundation",
  "Node.js": "Runtime JavaScript lato server caratterizzato da modello asincrono basato su event-loop, utilizzato per lo sviluppo di applicazioni backend",
  "Nonce": "Valore numerico monouso utilizzato in crittografia per prevenire attacchi replay e garantire freschezza dei messaggi",
  // O
  "OAuth2": "Standard di autorizzazione che consente l'accesso delegato ai servizi, permettendo l'autenticazione tramite provider terzi senza esporre le credenziali",
  "OCR": "Acronimo di Optical Character Recognition, tecnologia che consente di riconoscere e convertire testo contenuto in immagini in formato digitale",
  "ORM": "Acronimo di Object-Relational Mapping, tecnica che consente di mappare oggetti nel codice alle tabelle di un database relazionale",
  "OTA": "Acronimo di Over-The-Air, tecnologia che consente di aggiornare firmware o software di dispositivi remoti attraverso una connessione di rete",
  // P
  "PDCA": "Acronimo di Plan-Do-Check-Act, ciclo di miglioramento continuo che articola la gestione della qualità in quattro fasi: pianificazione, esecuzione, controllo e correzione",
  "Patch": "Il terzo numero nella notazione SemVer (X.Y.Z). Viene incrementato per correzioni minori, come errori di battitura o piccoli aggiustamenti che non alterano in alcun modo la struttura principale del documento.",
  "pipeline": "Sequenza automatizzata di processi (script) eseguiti da un sistema CI/CD per compilare, testare e verificare il codice o la documentazione",
  "POC": "Acronimo di Proof Of Concept, è una versione minimale e semplificata di un'idea o di un progetto software, creata per dimostrarne la fattibilità tecnica e la validità prima di investire risorse significative nello sviluppo completo, verificando se il concetto soddisfa gli obiettivi previsti e identificando precocemente rischi e problemi",
  "PostgreSQL": "Database relazionale open source caratterizzato da robustezza, conformità SQL avanzata e supporto di estensioni per casi d'uso specializzati",
  "Postman": "Strumento di sviluppo che consente di testare, documentare e condividere API tramite un'interfaccia intuitiva per richieste HTTP",
  "Prisma": "ORM moderno per Node.js e TypeScript che fornisce un'interfaccia type-safe per interagire con database relazionali, con generazione automatica di client",
  "Prometheus": "Sistema di monitoraggio e alerting open source che raccoglie metriche time-series da applicazioni e infrastruttura",
  "Provisioning": "Processo di allocazione e configurazione di risorse necessarie per il funzionamento di un sistema",
  "Pub/Sub": "Pattern di messaggistica dove produttori inviano messaggi a un broker e consumatori ricevono messaggi di loro interesse senza accoppiamento diretto",
  "pull-request": "Richiesta di integrazione di modifiche da un branch secondario al branch principale di un repository. Permette la revisione del codice prima dell'unione definitiva",
  "PR": "Abbreviazione di pull request. Utilizzata comunemente per indicare la richiesta di revisione o integrazione nel flusso di lavoro Git",
  // Q
  "Quality Gate": "Controllo automatico che verifica il rispetto di soglie minime di qualità prima di permettere integrazione o release del codice",
  // R
  "Rate Limiting": "Meccanismo di sicurezza che limita il numero di richieste da uno stesso client entro un intervallo temporale, prevenendo abusi e attacchi denial-of-service",
  "REST": "Acronimo di Representational State Transfer, stile architetturale per la progettazione di API basato su HTTP e rappresentazioni di risorse",
  "Retention Policy": "Politica che definisce il tempo per il quale i dati devono essere conservati nel sistema prima della loro eliminazione automatica",
  "Retrospective": "Riunione al termine di uno sprint dove il team analizza l'andamento, identifica miglioramenti e pianifica correzioni per il periodo successivo",
  "repository documentale": "Archivio centralizzato che contiene documenti, file e versioni, utilizzato per la gestione e la conservazione della documentazione di progetto",
  "repository": "Archivio centralizzato che può contiene solitamente codice sorgente, la documentazione e la cronologia delle versioni di un progetto",
  "Redis": "Database in-memory open source utilizzato come cache, message broker e archivio chiave-valore ad alte prestazioni",
  "Row-Level Security": "Meccanismo di sicurezza database che applica policy di accesso a livello di riga, garantendo segregazione dati in contesti multi-tenant",
  "RTB": "Acronimo di Requirements and Technology Baseline, milestone che rappresenta il primo punto di baseline formale del progetto con requisiti e tecnologie approvati",
  "Rule of Thumb": "Regola empirica o buona pratica. Indica un principio generale o una linea guida basata sull'esperienza pratica piuttosto che su una regola tecnica stretta. Permette di orientare le decisioni rapide durante lo sviluppo o la stesura.",
  // S
  "scripting": "Automazione di attività ripetitive tramite script eseguibili (build, pubblicazione, verifica, generazione documenti)",
  "Scrum Master": "Membro del team con il compito di facilitare l'applicazione del metodo Scrum, rimuovere ostacoli e promuovere buone pratiche di lavoro collaborativo",
  "Scrum": "Framework di sviluppo Agile basato su iterazioni (sprint) e ruoli definiti, volto a migliorare la collaborazione e la gestione del lavoro di gruppo",
  "SemVer": "Acronimo di Semantic Versioning. È lo standard di versionamento adottato dal gruppo (formato X.Y.Z), dove ogni numero ha un significato semantico preciso riguardo alla natura delle modifiche apportate, riflettendo le best practices del settore.",
  "Serverless": "Paradigma architetturale dove lo sviluppatore scrive funzioni isolate eseguite on-demand dal cloud provider senza gestione esplicita dell'infrastruttura",
  "Single Page Application": "Applicazione web che carica una singola pagina HTML e aggiorna dinamicamente il contenuto tramite JavaScript senza ricaricamenti completi",
  "SPA": "Acronimo di Single Page Application, applicazione web che carica una singola pagina HTML e aggiorna dinamicamente il contenuto senza ricaricamenti completi",
  "Smart Commits": "Meccanismo che crea collegamento automatico tra commit Git e issue Jira mediante inclusione dell'ID task nel messaggio di commit",
  "Smoke Testing": "Tipo di test rapido che verifica le funzionalità critiche principali del sistema senza approfondire i dettagli",
  "SonarQube": "Piattaforma Open Source sviluppata da Sonar per l'integrazione nei flussi di lavoro di sviluppo software, garantendo qualità e la sicurezza costanti nel codice",
  "Sprint Planning": "Fase iniziale di ogni sprint in cui il team definisce gli obiettivi e pianifica le attività da completare",
  "Sprint Review": "Cerimonia Scrum al termine dello sprint dove il team presenta i lavori completati e riceve feedback dagli stakeholder",
  "sprint": "Periodo di tempo prefissato, tipicamente di una o due settimane, durante il quale il team di sviluppo lavora su un insieme definito di attività",
  "Squash and Merge": "Operazione Git che combina tutti i commit di un feature branch in un singolo commit prima dell'integrazione nel ramo principale",
  "stakeholders": "Persone o entità interessate al progetto, che possono influenzarlo o esserne influenzate, come clienti, utenti, sviluppatori e sponsor",
  "struttura semantica": "Organizzazione di directory e file che esprime il significato (ruolo, ambito, stato) oltre al semplice contenimento",
  "Subgroups": "Sottodirectory situate all'interno di una directory Group. Servono a organizzare ulteriormente i documenti in categorie più specifiche.",
  "Subfiles": "File parziali (frammenti di codice o testo) che non costituiscono un documento autonomo, ma sono necessari per la compilazione del documento finale. Vengono inclusi nel file principale per mantenere il progetto modulare e gestibile.",
  "System Testing": "Metodologia di test che verifica il sistema completo end-to-end in ambiente simulato, includendo tutte le funzionalità integrate",
  "Snake Case": "Convenzione di scrittura in cui le parole sono separate da un trattino basso ( _ ) e scritte interamente in minuscolo (es. nome_del_file.typ). All'interno del gruppo, è lo standard adottato per la nomenclatura di file e directory per garantire compatibilità e ordine.",
  // T
  "Tailoring": "Processo di adattamento e selezione dei processi standard ISO a un contesto specifico di progetto, escludendo quelli non pertinenti",
  "task": "Unità di lavoro specifica e delimitata, generalmente associata a una singola attività o obiettivo da completare",
  "TBD": "Acronimo per To Be Defined (da definire). È un segnaposto utilizzato all'interno dei file .meta.yaml per indicare chiaramente la mancanza, al momento della modifica del documento, di un verificatore designato. In caso di presenza di tale campo la PR non può avere in alcun modo successo.",
  "Telemetria": "Raccolta e trasmissione automatica di dati di misurazione e diagnostica da dispositivi remoti a un sistema centrale per monitoraggio e analisi",
  "template Typst": "Modello predefinito scritto in linguaggio Typst, utilizzato per standardizzare la struttura grafica e formale dei documenti del gruppo",
  "template": "Struttura predefinita utilizzata come modello per la redazione uniforme dei documenti del progetto",
  "Tenant": "Entità cliente in un'architettura multi-tenancy che condivide l'infrastruttura ma con segregazione completa dei dati e delle risorse",
  "TimescaleDB": "Estensione PostgreSQL specializzata per dati time-series, ottimizzata per archiviazione efficiente e query ad alte prestazioni su dati temporali",
  "TLS": "Acronimo di Transport Layer Security, protocollo crittografico che garantisce comunicazione sicura su rete proteggendo dati in transito",
  "TOTP": "Acronimo per Time Based One Time Password, è un algoritmo che genera password temporanee, utilizzate per l'autenticazione a due fattori",
  "Trunk-Based Development": "Strategia di branching dove il ramo principale rimane sempre integro, con feature branch effimeri che si integrano frequentemente",
  "TypeScript": "Linguaggio di programmazione basato su JavaScript che aggiunge tipizzazione statica per migliore manutenibilità e rilevazione di errori in fase di sviluppo",
  "Typstyle": "Strumento automatico di formattazione per file Typst che applica regole di stile definite dal team garantendo coerenza",
  "Typst": "Linguaggio di composizione testuale per la creazione di documenti strutturati, caratterizzato da una sintassi chiara e moderna, alternativo a LaTeX e adatto all'automazione della documentazione",
  // U
  "Unit Testing": "Metodologia di test che verifica singole unità di codice isolate garantendone la correttezza funzionale in isolamento",
  "UUID": "Identificatore universale univoco formato da 128 bit, utilizzato per garantire unicità globale di identificatori in sistemi distribuiti senza coordinamento centralizzato",
  // V
  "Vendor Lock-in": "Situazione dove un'organizzazione diventa dipendente da una specifica piattaforma proprietaria, rendendo difficile e costoso cambiare fornitore o migrare altrove",
  "Verificatore": "Ruolo responsabile della revisione indipendente di documenti/artefatti per garantirne conformità, qualità e tracciabilità",
  "version control": "Sistema che consente di registrare, monitorare e gestire le modifiche al codice sorgente o ai documenti di progetto nel tempo, garantendo tracciabilità e collaborazione",
  "versionamento": "Processo di gestione e numerazione progressiva delle versioni dei documenti o del codice per garantire tracciabilità e ordine",
  // W
  "Way of Working": "Documento o insieme di pratiche che descrive le modalità operative, gli strumenti e le regole adottate dal team per collaborare in modo efficace e coerente",
  "WebSocket": "Protocollo che abilita comunicazione full-duplex a bassa latenza su una singola connessione TCP, essenziale per streaming di dati in tempo reale",
  // X
  // Y
  "YAML": "Formato di serializzazione leggibile da umani, usato per file di metadati e configurazione (es. .meta.yaml)",
  // Z
  "Zero Trust": "Paradigma di sicurezza dove nessuna entità è considerata affidabile per default, richiedendo verifica continua per ogni accesso",
)
