@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Provisioned Gateway" as CA_p_gway
actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC67 - Aggiornamento del firmware Gateway" as aggiornamento_firmware_gateway
    usecase "UC67.1 - Selezione firmware" as selezione_firmware
    usecase "UC68 - Selezione Gateway" as selezione_gateway
}

CA_tenant_adm -right-> aggiornamento_firmware_gateway
aggiornamento_firmware_gateway -right-> CA_p_gway
aggiornamento_firmware_gateway -down..> selezione_gateway : <<include>>
aggiornamento_firmware_gateway -down..> selezione_firmware : <<include>>
@enduml