@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC30 - Ricezione alert Gateway non raggiungibile" as alert_gateway_irraggiungibile
    usecase "UC19 - Visualizzazione nome Gateway" as visualizzazione_nome_gateway
    usecase "UC22 - Visualizzazione timestamp ultimo invio dati Gateway" as visualizzazione_timestamp_ultimo_invio_dati_gateway
}

CA_tenant_usr -right-> alert_gateway_irraggiungibile
alert_gateway_irraggiungibile -down..> visualizzazione_nome_gateway : <<include>>
alert_gateway_irraggiungibile -down..> visualizzazione_timestamp_ultimo_invio_dati_gateway : <<include>>
@enduml