@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC52 - Creazione Utente del Tenant" as creazione_utente_tenant
    usecase "UC13 - Impostazione mail" as impostazione_mail
    usecase "UC9 - Impostazione password" as impostazione_password
    usecase "UC52.1 - Inserimento nome Utente" as inserimento_nome_utente
    usecase "UC54 - Selezione permessi Utente" as selezione_permessi_utente
}

CA_tenant_adm -right-> creazione_utente_tenant
creazione_utente_tenant -down..> inserimento_nome_utente : <<include>>
creazione_utente_tenant -down..> selezione_permessi_utente : <<include>>
creazione_utente_tenant -down..> impostazione_mail : <<include>>
creazione_utente_tenant -down..> impostazione_password : <<include>>
@enduml