@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC94 - Creazione Utente Amministratore Tenant" as creazione_utente_amministratore_tenant
    usecase "UC13 - Impostazione mail" as impostazione_mail
    usecase "UC9 - Impostazione password" as impostazione_password
}

CA_sys_adm -right-> creazione_utente_amministratore_tenant
creazione_utente_amministratore_tenant -down..> impostazione_mail : <<include>>
creazione_utente_amministratore_tenant -down..> impostazione_password : <<include>>
@enduml