@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm
actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC65.2 - Download log Audit esportati" as download_log_audit_esportati
}

CA_tenant_adm -right-> download_log_audit_esportati
CA_sys_adm -right-> download_log_audit_esportati
@enduml