@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC91.1 - Conferma eliminazione Tenant" as conferma_eliminazione_tenant
    usecase "UC91 - Eliminazione Tenant" as eliminazione_tenant
}

CA_sys_adm -right-> eliminazione_tenant
eliminazione_tenant -down..> conferma_eliminazione_tenant : <<include>>
@enduml