@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Autenticato" as CA_authd_usr

rectangle "Sistema" {
    usecase "UC14 - Errore Mail non valida" as err_mail_non_valida
}

CA_authd_usr -right-> err_mail_non_valida
@enduml