@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Autenticato" as CA_authd_usr
actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC11 - Errore password non valida" as err_password_invalida
}

CA_non_authd_usr -right-> err_password_invalida
CA_authd_usr -right-> err_password_invalida
@enduml