@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Client API" as CA_api_client

rectangle "Sistema" {
    usecase "UC77 - Errore intervallo Temporale Invalido" as err_intervallo_temporale_invalido
}

CA_api_client -right-> err_intervallo_temporale_invalido
@enduml