@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Client API" as CA_api_client

rectangle "Sistema" {
    usecase "UC74 - Errore token autenticazione API invalido" as err_token_api_invalido
}

CA_api_client -right-> err_token_api_invalido
@enduml