@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC100 - Errore range invalido" as err_range_invalido
}

CA_tenant_adm -right-> err_range_invalido
@enduml