@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC8 - Errore account non esistente" as err_account_inesistente
}

CA_non_authd_usr -right-> err_account_inesistente
@enduml