@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Not Provisioned Gateway" as CA_np_gway

rectangle "Sistema" {
    usecase "UC97 - Errore autenticazione Gateway di fabbrica" as err_auth_gateway_fabbrica
}

CA_np_gway -right-> err_auth_gateway_fabbrica
@enduml