@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Autenticato" as CA_authd_usr

rectangle "Sistema" {
    usecase "UC15 - Errore mail duplicata" as err_mail_gia_registrata
}

CA_authd_usr -right-> err_mail_gia_registrata
@enduml