@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC2 - Errore credenziali errate" as err_cred_errate
}

CA_non_authd_usr -right-> err_cred_errate
@enduml