@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Client API" as CA_api_client
actor "Auth Server" as CSA_auth_server

rectangle "Sistema" {
    usecase "UC71 - Errore dati di autenticazione non validi" as err_dati_autenticazione_invalidi
}

CA_api_client -right-> err_dati_autenticazione_invalidi
err_dati_autenticazione_invalidi -right-> CSA_auth_server
@enduml