@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC87 - Errore interno creazione Tenant" as err_interno_creazione_tenant
}

CA_sys_adm -right-> err_interno_creazione_tenant
@enduml