@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC28 - Errore dati non disponibili" as err_dati_non_disponibili
}

CA_tenant_usr -right-> err_dati_non_disponibili
@enduml