@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Client API" as CA_api_client
actor "Auth Server" as CSA_auth_server

rectangle "Sistema" {
    usecase "UC72 - Errore Auth Server non disponibile" as err_auth_server_non_disponibile
}

CA_api_client -right-> err_auth_server_non_disponibile
err_auth_server_non_disponibile -right-> CSA_auth_server
@enduml