@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm
actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC65.2 - Download log Audit esportati" as download_log_audit_esportati
    usecase "UC65 - Esportazione log di Audit del Tenant" as esportazione_log_audit_tenant
    usecase "UC65.1 - Selezione intervallo temporale" as selezione_intervallo_temporale
    usecase "UC88 - Selezione Tenant" as selezione_tenant
}

CA_tenant_adm -right-> esportazione_log_audit_tenant
CA_sys_adm -right-> esportazione_log_audit_tenant
esportazione_log_audit_tenant -down..> selezione_tenant : <<include>>
esportazione_log_audit_tenant -down..> selezione_intervallo_temporale : <<include>>
esportazione_log_audit_tenant -down..> download_log_audit_esportati : <<include>>
@enduml