@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC29.2 - Esportazione dati in formato JSON" as esportazione_dati_json
}

CA_tenant_usr -right-> esportazione_dati_json
@enduml