@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC101 - Inserimento mail" as ins_mail
}

CA_non_authd_usr -right-> ins_mail
@enduml