@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC93.1 - Inserimento credenziali di fabbrica Gateway" as inserimento_credenziali_fabbrica_gateway
}

CA_sys_adm -right-> inserimento_credenziali_fabbrica_gateway
@enduml