@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Autenticato" as CA_authd_usr
actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC9.1 - Inserimento nuova password" as inserimento_nuova_password
}

CA_non_authd_usr -right-> inserimento_nuova_password
CA_authd_usr -right-> inserimento_nuova_password
@enduml