@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Autenticato" as CA_authd_usr

rectangle "Sistema" {
    usecase "UC15 - Errore mail duplicata" as err_mail_gia_registrata
    usecase "UC14 - Errore Mail non valida" as err_mail_non_valida
    usecase "UC13.1 - Inserimento mail" as inserimento_nuova_mail
}

CA_authd_usr -right-> inserimento_nuova_mail
err_mail_non_valida .up.> inserimento_nuova_mail : <<extend>>
note on link
  EP: MailInvalida
  Condition: L’Attore inserisce una mail non valida
end note
err_mail_gia_registrata .up.> inserimento_nuova_mail : <<extend>>
note on link
  EP: MailInvalida
  Condition: L’Attore inserisce una mail già associata ad un altro account
end note
@enduml