@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC45 - Inserimento valore numerico" as inserimento_valore_numerico
}

CA_tenant_adm -right-> inserimento_valore_numerico
@enduml