@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Provisioned Gateway" as CA_p_gway

rectangle "Sistema" {
    usecase "UC98.1 - Instaurazione connessione sicura" as instaurazione_connessione_sicura
    usecase "UC98 - Invio dati crittografati al Cloud" as invio_dati_crittografati_cloud
}

CA_p_gway -right-> invio_dati_crittografati_cloud
invio_dati_crittografati_cloud -down..> instaurazione_connessione_sicura : <<include>>
@enduml