@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC5 - Inserimento OTP" as ins_otp
    usecase "UC4 - Login 2FA" as login_2fa
}

CA_non_authd_usr -right-> login_2fa
login_2fa -down..> ins_otp : <<include>>
@enduml