@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC66 - Modifica impostazioni impersonificazione" as modifica_impostazioni_impersonificazione
}

CA_tenant_adm -right-> modifica_impostazioni_impersonificazione
@enduml