@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC39 - Modifica impostazioni notifica alert via dashboard" as modifica_impostazioni_notifica_alert_dashboard
}

CA_tenant_usr -right-> modifica_impostazioni_notifica_alert_dashboard
@enduml