@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Provisioned Gateway" as CA_p_gway
actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC45 - Inserimento valore numerico" as inserimento_valore_numerico
    usecase "UC69 - Modifica frequenza invio dati Gateway specifico" as modifica_frequenza_invio_gateway
    usecase "UC68 - Selezione Gateway" as selezione_gateway
}

CA_tenant_adm -right-> modifica_frequenza_invio_gateway
modifica_frequenza_invio_gateway -right-> CA_p_gway
modifica_frequenza_invio_gateway -down..> selezione_gateway : <<include>>
modifica_frequenza_invio_gateway -down..> inserimento_valore_numerico : <<include>>
@enduml