@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Provisioned Gateway" as CA_p_gway
actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC42 - Modifica stato del Gateway" as modifica_stato_gateway
    usecase "UC42.1 - Selezione stato del Gateway" as selezione_stato_gateway
}

CA_tenant_adm -right-> modifica_stato_gateway
modifica_stato_gateway -right-> CA_p_gway
modifica_stato_gateway -down..> selezione_stato_gateway : <<include>>
@enduml