@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC41 - Errore nome Gateway duplicato" as err_nome_gateway_duplicato
    usecase "UC40 - Modifica nome Gateway" as modifica_nome_gateway
}

CA_tenant_adm -right-> modifica_nome_gateway
err_nome_gateway_duplicato .up.> modifica_nome_gateway : <<extend>>
note on link
  EP: NomeDuplicato
  Condition: Il nome inserito è già assegnato ad un altro Gateway nel Tenant
end note
@enduml