@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC63 - Modifica impostazioni 2FA login dashboard" as modifica_impostazioni_2fa
}

CA_tenant_adm -right-> modifica_impostazioni_2fa
@enduml