@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC9 - Impostazione password" as impostazione_password
    usecase "UC57 - Modifica password Utente del Tenant" as modifica_password_utente
}

CA_tenant_adm -right-> modifica_password_utente
modifica_password_utente -down..> impostazione_password : <<include>>
@enduml