@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC55 - Modifica permessi Utente del Tenant" as modifica_permessi_utente
    usecase "UC54 - Selezione permessi Utente" as selezione_permessi_utente
    usecase "UC53 - Selezione Utente Tenant" as selezione_utente_tenant
}

CA_tenant_adm -right-> modifica_permessi_utente
modifica_permessi_utente -down..> selezione_utente_tenant : <<include>>
modifica_permessi_utente -down..> selezione_permessi_utente : <<include>>
@enduml