@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Autenticato" as CA_authd_usr

rectangle "Sistema" {
    usecase "UC9 - Impostazione password" as impostazione_password
    usecase "UC16 - Modifica password account" as modifica_password_account
}

CA_authd_usr -right-> modifica_password_account
modifica_password_account -down..> impostazione_password : <<include>>
@enduml