@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC95.3 - Monitoraggio Storage" as monitoraggio_storage
}

CA_sys_adm -right-> monitoraggio_storage
@enduml