@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC95.1 - Monitoraggio latenza" as monitoraggio_latenza
    usecase "UC95 - Monitoraggio performance Sistema" as monitoraggio_performance_sistema
    usecase "UC95.3 - Monitoraggio Storage" as monitoraggio_storage
    usecase "UC95.2 - Monitoraggio Volumi di Traffico" as monitoraggio_volumi_traffico
}

CA_sys_adm -right-> monitoraggio_performance_sistema
monitoraggio_performance_sistema -down..> monitoraggio_latenza : <<include>>
monitoraggio_performance_sistema -down..> monitoraggio_volumi_traffico : <<include>>
monitoraggio_performance_sistema -down..> monitoraggio_storage : <<include>>
@enduml