@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Non Autenticato" as CA_non_authd_usr

rectangle "Sistema" {
    usecase "UC8 - Errore account non esistente" as err_account_inesistente
    usecase "UC101 - Inserimento mail" as ins_mail
    usecase "UC7 - Recupero password" as recupero_password
}

CA_non_authd_usr -right-> recupero_password
recupero_password -down..> ins_mail : <<include>>
err_account_inesistente .up.> recupero_password : <<extend>>
note on link
  EP: UtenteInesistente
  Condition: L
end note
@enduml