@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC93.1 - Inserimento credenziali di fabbrica Gateway" as inserimento_credenziali_fabbrica_gateway
    usecase "UC93 - Provisioning Gateway - Registrazione e associazione Tenant" as registrazione_associazione_gateway
    usecase "UC88 - Selezione Tenant" as selezione_tenant
}

CA_sys_adm -right-> registrazione_associazione_gateway
registrazione_associazione_gateway -down..> selezione_tenant : <<include>>
registrazione_associazione_gateway -down..> inserimento_credenziali_fabbrica_gateway : <<include>>
@enduml