@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC90 - Riattivazione Tenant" as riattivazione_tenant
    usecase "UC88 - Selezione Tenant" as selezione_tenant
}

CA_sys_adm -right-> riattivazione_tenant
riattivazione_tenant -down..> selezione_tenant : <<include>>
@enduml