@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Client API" as CA_api_client

rectangle "Sistema" {
    usecase "UC75 - Errore ID Gateway invalido" as err_id_gateway_invalido
    usecase "UC76 - Errore ID Sensore invalido" as err_id_sensore_invalido
    usecase "UC77 - Errore intervallo Temporale Invalido" as err_intervallo_temporale_invalido
    usecase "UC74 - Errore token autenticazione API invalido" as err_token_api_invalido
    usecase "UC73 - Richiesta dati On-Demand" as richiesta_dati_on_demand
}

CA_api_client -right-> richiesta_dati_on_demand
err_token_api_invalido .up.> richiesta_dati_on_demand : <<extend>>
note on link
  EP: DatiNonValidi
  Condition: Il token fornito dall’Utente non è valido
end note
err_id_gateway_invalido .up.> richiesta_dati_on_demand : <<extend>>
note on link
  EP: DatiNonValidi
  Condition: ID Gateway invalido
end note
err_id_sensore_invalido .up.> richiesta_dati_on_demand : <<extend>>
note on link
  EP: DatiNonValidi
  Condition: ID sensore invalido
end note
err_intervallo_temporale_invalido .up.> richiesta_dati_on_demand : <<extend>>
note on link
  EP: DatiNonValidi
  Condition: Intervallo temporale malformato
end note
@enduml