@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC54 - Selezione permessi Utente" as selezione_permessi_utente
}

CA_tenant_adm -right-> selezione_permessi_utente
@enduml