@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC45 - Inserimento valore numerico" as inserimento_valore_numerico
    usecase "UC44 - Selezione range numerico misurazioni" as selezione_range_numerico
}

CA_tenant_adm -right-> selezione_range_numerico
selezione_range_numerico -down..> inserimento_valore_numerico : <<include>>
selezione_range_numerico -down..> inserimento_valore_numerico : <<include>>
@enduml