@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm
actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC68 - Selezione Gateway" as selezione_gateway
}

CA_tenant_adm -right-> selezione_gateway
CA_sys_adm -right-> selezione_gateway
@enduml