@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC62.1 - Selezione credenziali client API" as selezione_credenziali_api
}

CA_tenant_adm -right-> selezione_credenziali_api
@enduml