@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente Non Autenticato" as CA_non_authd_usr
actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC5 - Inserimento OTP" as ins_otp
    usecase "UC3 - Setup TOTP" as setup_totp
}

CA_non_authd_usr -right-> setup_totp
CA_sys_adm -right-> setup_totp
setup_totp -down..> ins_otp : <<include>>
@enduml