@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC88 - Selezione Tenant" as selezione_tenant
    usecase "UC89 - Sospensione Tenant" as sospensione_tenant
}

CA_sys_adm -right-> sospensione_tenant
sospensione_tenant -down..> selezione_tenant : <<include>>
@enduml