@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC21 - Visualizzazione dettagli Gateway" as visualizzazione_dettagli_gateway
    usecase "UC22.1 - Visualizzazione lista sensori" as visualizzazione_lista_sensori
    usecase "UC19 - Visualizzazione nome Gateway" as visualizzazione_nome_gateway
    usecase "UC20 - Visualizzazione stato Gateway" as visualizzazione_stato_gateway
    usecase "UC22 - Visualizzazione timestamp ultimo invio dati Gateway" as visualizzazione_timestamp_ultimo_invio_dati_gateway
}

CA_tenant_usr -right-> visualizzazione_dettagli_gateway
visualizzazione_dettagli_gateway -down..> visualizzazione_nome_gateway : <<include>>
visualizzazione_dettagli_gateway -down..> visualizzazione_stato_gateway : <<include>>
visualizzazione_dettagli_gateway -down..> visualizzazione_timestamp_ultimo_invio_dati_gateway : <<include>>
visualizzazione_dettagli_gateway -down..> visualizzazione_lista_sensori : <<include>>
@enduml