@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC61.1.1 - Visualizzazione nome descrittivo credenziali API" as visualizzazione_nome_descrittivo_api
}

CA_tenant_adm -right-> visualizzazione_nome_descrittivo_api
@enduml