@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC33.1.1 - Visualizzazione tipo di alert" as visualizzazione_tipo_alert
}

CA_tenant_usr -right-> visualizzazione_tipo_alert
@enduml