@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC51 - Visualizzazione mail dell’Utente" as visualizzazione_mail_utente
    usecase "UC50.1.2 - Visualizzazione nome dell’Utente" as visualizzazione_nome_utente
    usecase "UC50.1.1 - Visualizzazione ruolo dell’Utente" as visualizzazione_ruolo_utente
    usecase "UC50.1 - Visualizzazione singolo Utente del Tenant" as visualizzazione_singolo_utente_tenant
    usecase "UC50.1.3 - Visualizzazione ultimo accesso dell’Utente" as visualizzazione_ultimo_accesso_utente
}

CA_tenant_adm -right-> visualizzazione_singolo_utente_tenant
visualizzazione_singolo_utente_tenant -down..> visualizzazione_ruolo_utente : <<include>>
visualizzazione_singolo_utente_tenant -down..> visualizzazione_nome_utente : <<include>>
visualizzazione_singolo_utente_tenant -down..> visualizzazione_mail_utente : <<include>>
visualizzazione_singolo_utente_tenant -down..> visualizzazione_ultimo_accesso_utente : <<include>>
@enduml