@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC82 - Visualizzazione stato Tenant" as visualizzazione_stato_tenant
}

CA_sys_adm -right-> visualizzazione_stato_tenant
@enduml