@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC49.1 - Visualizzazione costi stimati per storage" as visualizzazione_costi_storage
}

CA_tenant_adm -right-> visualizzazione_costi_storage
@enduml