@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC50 - Visualizzazione lista Utenti del Tenant" as visualizzazione_lista_utenti_tenant
    usecase "UC50.1 - Visualizzazione singolo Utente del Tenant" as visualizzazione_singolo_utente_tenant
}

CA_tenant_adm -right-> visualizzazione_lista_utenti_tenant
visualizzazione_lista_utenti_tenant -down..> visualizzazione_singolo_utente_tenant : <<include>>
@enduml