@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC24.2 - Visualizzazione grafico dati Stream" as visualizzazione_grafico_dati_stream
}

CA_tenant_usr -right-> visualizzazione_grafico_dati_stream
@enduml