@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC23 - Visualizzazione ID sensore" as visualizzazione_id_sensore
    usecase "UC22.1.1 - Visualizzazione singolo sensore" as visualizzazione_singolo_sensore
    usecase "UC22.1.1.1 - Visualizzazione timestamp ultimo invio dati sensore" as visualizzazione_timestamp_ultimo_invio_dati_sensore
}

CA_tenant_usr -right-> visualizzazione_singolo_sensore
visualizzazione_singolo_sensore -down..> visualizzazione_id_sensore : <<include>>
visualizzazione_singolo_sensore -down..> visualizzazione_timestamp_ultimo_invio_dati_sensore : <<include>>
@enduml