@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC33.1.2 - Visualizzazione hardware interessato" as visualizzazione_hardware_interessato
}

CA_tenant_usr -right-> visualizzazione_hardware_interessato
@enduml