@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC19 - Visualizzazione nome Gateway" as visualizzazione_nome_gateway
}

CA_tenant_usr -right-> visualizzazione_nome_gateway
@enduml