@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC83 - Visualizzazione ID Tenant" as visualizzazione_id_tenant
    usecase "UC81 - Visualizzazione nome Tenant" as visualizzazione_nome_tenant
    usecase "UC79.1 - Visualizzazione singolo Tenant" as visualizzazione_singolo_tenant
    usecase "UC82 - Visualizzazione stato Tenant" as visualizzazione_stato_tenant
}

CA_sys_adm -right-> visualizzazione_singolo_tenant
visualizzazione_singolo_tenant -down..> visualizzazione_nome_tenant : <<include>>
visualizzazione_singolo_tenant -down..> visualizzazione_stato_tenant : <<include>>
visualizzazione_singolo_tenant -down..> visualizzazione_id_tenant : <<include>>
@enduml