@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC60 - Visualizzazione Client ID" as visualizzazione_client_id
    usecase "UC51 - Visualizzazione mail dell’Utente" as visualizzazione_mail_utente
    usecase "UC61.1.1 - Visualizzazione nome descrittivo credenziali API" as visualizzazione_nome_descrittivo_api
    usecase "UC61.1 - Visualizzazione singole credenziali API del Tenant" as visualizzazione_singole_api
    usecase "UC61.1.2 - Visualizzazione timestamp creazione credenziali API" as visualizzazione_timestamp_api
}

CA_tenant_adm -right-> visualizzazione_singole_api
visualizzazione_singole_api -down..> visualizzazione_nome_descrittivo_api : <<include>>
visualizzazione_singole_api -down..> visualizzazione_client_id : <<include>>
visualizzazione_singole_api -down..> visualizzazione_mail_utente : <<include>>
visualizzazione_singole_api -down..> visualizzazione_timestamp_api : <<include>>
@enduml