@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC61.1.2 - Visualizzazione timestamp creazione credenziali API" as visualizzazione_timestamp_api
}

CA_tenant_adm -right-> visualizzazione_timestamp_api
@enduml