@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC23 - Visualizzazione ID sensore" as visualizzazione_id_sensore
}

CA_tenant_usr -right-> visualizzazione_id_sensore
@enduml