@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC22.1.1.1 - Visualizzazione timestamp ultimo invio dati sensore" as visualizzazione_timestamp_ultimo_invio_dati_sensore
}

CA_tenant_usr -right-> visualizzazione_timestamp_ultimo_invio_dati_sensore
@enduml