@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC31.2 - Visualizzazione range accettato" as visualizzazione_range_accettato
}

CA_tenant_usr -right-> visualizzazione_range_accettato
@enduml