@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC19 - Visualizzazione nome Gateway" as visualizzazione_nome_gateway
    usecase "UC18.1 - Visualizzazione singolo Gateway" as visualizzazione_singolo_gateway
    usecase "UC20 - Visualizzazione stato Gateway" as visualizzazione_stato_gateway
}

CA_tenant_usr -right-> visualizzazione_singolo_gateway
visualizzazione_singolo_gateway -down..> visualizzazione_nome_gateway : <<include>>
visualizzazione_singolo_gateway -down..> visualizzazione_stato_gateway : <<include>>
@enduml