@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC79 - Visualizzazione lista Tenant" as visualizzazione_lista_tenant
    usecase "UC79.1 - Visualizzazione singolo Tenant" as visualizzazione_singolo_tenant
}

CA_sys_adm -right-> visualizzazione_lista_tenant
visualizzazione_lista_tenant -down..> visualizzazione_singolo_tenant : <<include>>
@enduml