@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC51 - Visualizzazione mail dell’Utente" as visualizzazione_mail_utente
}

CA_tenant_adm -right-> visualizzazione_mail_utente
@enduml