@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Provisioned Gateway" as CA_p_gway
actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC28 - Errore dati non disponibili" as err_dati_non_disponibili
    usecase "UC24 - Visualizzazione dati Stream" as visualizzazione_dati_stream
    usecase "UC24.2 - Visualizzazione grafico dati Stream" as visualizzazione_grafico_dati_stream
    usecase "UC24.1 - Visualizzazione tabellare dati Stream" as visualizzazione_tabellare_dati_stream
}

CA_tenant_usr -right-> visualizzazione_dati_stream
visualizzazione_dati_stream -right-> CA_p_gway
visualizzazione_dati_stream -down..> visualizzazione_tabellare_dati_stream : <<include>>
visualizzazione_dati_stream -down..> visualizzazione_grafico_dati_stream : <<include>>
err_dati_non_disponibili .up.> visualizzazione_dati_stream : <<extend>>
note on link
  EP: NessunDato
  Condition: Non ci sono dati da visualizzare
end note
@enduml