@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC32 - Visualizzazione timestamp registrazione dato irregolare" as visualizzazione_timestamp_dato_irregolare
}

CA_tenant_usr -right-> visualizzazione_timestamp_dato_irregolare
@enduml