@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant Admin" as CA_tenant_adm

rectangle "Sistema" {
    usecase "UC50.1.2 - Visualizzazione nome dell’Utente" as visualizzazione_nome_utente
}

CA_tenant_adm -right-> visualizzazione_nome_utente
@enduml