@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Amministratore di Sistema" as CA_sys_adm

rectangle "Sistema" {
    usecase "UC88 - Selezione Tenant" as selezione_tenant
    usecase "UC80 - Visualizzazione dettagli Tenant" as visualizzazione_dettagli_tenant
    usecase "UC83 - Visualizzazione ID Tenant" as visualizzazione_id_tenant
    usecase "UC83.1 - Visualizzazione intervallo minimo di sospensione pre-eliminazione" as visualizzazione_intervallo_sospensione_tenant
    usecase "UC81 - Visualizzazione nome Tenant" as visualizzazione_nome_tenant
    usecase "UC82 - Visualizzazione stato Tenant" as visualizzazione_stato_tenant
}

CA_sys_adm -right-> visualizzazione_dettagli_tenant
visualizzazione_dettagli_tenant -down..> selezione_tenant : <<include>>
visualizzazione_dettagli_tenant -down..> visualizzazione_nome_tenant : <<include>>
visualizzazione_dettagli_tenant -down..> visualizzazione_stato_tenant : <<include>>
visualizzazione_dettagli_tenant -down..> visualizzazione_id_tenant : <<include>>
visualizzazione_dettagli_tenant -down..> visualizzazione_intervallo_sospensione_tenant : <<include>>
@enduml