@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC20.2 - Visualizzazione Gateway Offline" as visualizzazione_gateway_offline
}

CA_tenant_usr -right-> visualizzazione_gateway_offline
@enduml