@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC36 - Visualizzazione dettagli alert Gateway non raggiungibile" as visualizzazione_dettagli_alert_gateway_irraggiungibile
    usecase "UC19 - Visualizzazione nome Gateway" as visualizzazione_nome_gateway
    usecase "UC22 - Visualizzazione timestamp ultimo invio dati Gateway" as visualizzazione_timestamp_ultimo_invio_dati_gateway
}

CA_tenant_usr -right-> visualizzazione_dettagli_alert_gateway_irraggiungibile
visualizzazione_dettagli_alert_gateway_irraggiungibile -down..> visualizzazione_nome_gateway : <<include>>
visualizzazione_dettagli_alert_gateway_irraggiungibile -down..> visualizzazione_timestamp_ultimo_invio_dati_gateway : <<include>>
@enduml