@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC31.1 - Visualizzazione valore del dato registrato" as visualizzazione_valore_dato_registrato
}

CA_tenant_usr -right-> visualizzazione_valore_dato_registrato
@enduml