@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Tenant User" as CA_tenant_usr

rectangle "Sistema" {
    usecase "UC35 - Visualizzazione dettagli singolo alert" as visualizzazione_dettagli_singolo_alert
    usecase "UC34 - Visualizzazione timestamp emissione alert" as visualizzazione_timestamp_emissione_alert
}

CA_tenant_usr -right-> visualizzazione_dettagli_singolo_alert
visualizzazione_dettagli_singolo_alert -down..> visualizzazione_timestamp_emissione_alert : <<include>>
@enduml