# Note: this is a temporary solution. The team will switch to devcontainers soon, so this won't be needed anymore.

name: 'Setup Docs Environment'
description: 'Sets up Python, Typst, and installs project dependencies.'

runs:
  using: "composite"
  steps:
    - name: Install Hunspell
      run: |
        sudo apt-get update
        sudo apt-get install -y hunspell
      shell: bash

    - name: Install typstyle
      run: cargo install typstyle --locked
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install Typst
      uses: typst-community/setup-typst@v3


    - name: Install Python dependencies
      run: pip install -r notipdo/requirements.txt
      shell: bash

    - name: Install `notipdo` tool
      run: pip install notipdo/
      shell: bash
