@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS19 - Comando anomalia sensore - outliers nelle misurazioni" as comando_anomalia_outliers_misurazioni
    usecase "UCS16 - Errore valore numerico invalido" as err_valore_numerico_invalido
    usecase "UCS12.1.1 - Inserimento range generazione dati" as inserimento_range_generazione_dati
}

SA_sym_usr -right-> comando_anomalia_outliers_misurazioni
comando_anomalia_outliers_misurazioni -down..> inserimento_range_generazione_dati : <<include>>
err_valore_numerico_invalido .up.> comando_anomalia_outliers_misurazioni : <<extend>>
note on link
  EP: ValoreNumericoInvalido
  Condition: È stato inserito un valore numerico non valido
end note
@enduml