@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS10 - Creazione e Deploy di un Gateway simulato" as creazione_deploy_gateway_simulato
    usecase "UCS11 - Errore Deploy Gateway simulato" as err_deploy_gateway_simulato
    usecase "UCS10.1 - Inserimento dati configurazione simulazione gateway" as inserimento_dati_config_sim_gateway
}

SA_sym_usr -right-> creazione_deploy_gateway_simulato
creazione_deploy_gateway_simulato -down..> inserimento_dati_config_sim_gateway : <<include>>
err_deploy_gateway_simulato .up.> creazione_deploy_gateway_simulato : <<extend>>
note on link
  EP: ErroreDeploy
  Condition: Errore di sistema nella creazione delle istanze
end note
@enduml