@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS9 - Eliminazione sensore simulato" as eliminazione_sensore_simulato
}

SA_sym_usr -right-> eliminazione_sensore_simulato
@enduml