@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS16 - Errore valore numerico invalido" as err_valore_numerico_invalido
}

SA_sym_usr -right-> err_valore_numerico_invalido
@enduml