@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS13 - Errore range invalido del sensore simulato" as err_range_invalido_simulazione
}

SA_sym_usr -right-> err_range_invalido_simulazione
@enduml