@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Sistema Cloud" as SA_cloud

rectangle "Sistema" {
    usecase "UCS21 - Errore sintattico configurazione Gateway" as err_sintattico_config_gateway
}

SA_cloud -right-> err_sintattico_config_gateway
@enduml