@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS11 - Errore Deploy Gateway simulato" as err_deploy_gateway_simulato
}

SA_sym_usr -right-> err_deploy_gateway_simulato
@enduml