@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS14 - Errore creazione Sensore simulato" as err_creazione_sensore_simulato
}

SA_sym_usr -right-> err_creazione_sensore_simulato
@enduml