@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Sistema Cloud" as SA_cloud

rectangle "Sistema" {
    usecase "UCS22 - Errore configurazione frequenza invio dati fuori range ammesso" as err_config_frequenza_fuori_range
}

SA_cloud -right-> err_config_frequenza_fuori_range
@enduml