@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Sistema Cloud" as SA_cloud

rectangle "Sistema" {
    usecase "UCS22 - Errore configurazione frequenza invio dati fuori range ammesso" as err_config_frequenza_fuori_range
    usecase "UCS21 - Errore sintattico configurazione Gateway" as err_sintattico_config_gateway
    usecase "UCS20 - Impostazione configurazione del Gateway" as impostazione_configurazione_gateway
    usecase "UCS20.1 - Impostazione frequenza di invio dati" as impostazione_frequenza_invio_dati
    usecase "UCS20.2 - Impostazione stato sospensione" as impostazione_stato_sospensione
}

SA_cloud -right-> impostazione_configurazione_gateway
impostazione_configurazione_gateway -down..> impostazione_frequenza_invio_dati : <<include>>
impostazione_configurazione_gateway -down..> impostazione_stato_sospensione : <<include>>
err_sintattico_config_gateway .up.> impostazione_configurazione_gateway : <<extend>>
note on link
  EP: ConfigurazioneInvalida
  Condition: Il messaggio contiene errori di sintassi o un formato non riconosciuto
end note
err_config_frequenza_fuori_range .up.> impostazione_configurazione_gateway : <<extend>>
note on link
  EP: ConfigurazioneInvalida
  Condition: La frequenza richiesta non è supportata dal Gateway simulato
end note
@enduml