@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS13 - Errore range invalido del sensore simulato" as err_range_invalido_simulazione
    usecase "UCS12.1.1 - Inserimento range generazione dati" as inserimento_range_generazione_dati
}

SA_sym_usr -right-> inserimento_range_generazione_dati
err_range_invalido_simulazione .up.> inserimento_range_generazione_dati : <<extend>>
note on link
  EP: ErroreRangeInvalido
  Condition: I valori inseriti non sono validi
end note
@enduml