@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS10.1 - Inserimento dati configurazione simulazione gateway" as inserimento_dati_config_sim_gateway
}

SA_sym_usr -right-> inserimento_dati_config_sim_gateway
@enduml