@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS12.1 - Inserimento dati configurazione simulazione sensore" as inserimento_dati_config_sim_sensore
    usecase "UCS12.1.1 - Inserimento range generazione dati" as inserimento_range_generazione_dati
}

SA_sym_usr -right-> inserimento_dati_config_sim_sensore
inserimento_dati_config_sim_sensore -down..> inserimento_range_generazione_dati : <<include>>
@enduml