@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS5.2 - Visualizzazione algoritmo generazione dati" as visualizzazione_algoritmo_generazione_dati
}

SA_sym_usr -right-> visualizzazione_algoritmo_generazione_dati
@enduml