@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS3.1 - Visualizzazione chiave di fabbrica simulazione" as visualizzazione_chiave_fabbrica_simulazione
}

SA_sym_usr -right-> visualizzazione_chiave_fabbrica_simulazione
@enduml