@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS1.1.1 - Visualizzazione data di creazione del Gateway Simulato" as visualizzazione_data_creazione_simulazione
    usecase "UCS2 - Visualizzazione ID di fabbrica simulazione" as visualizzazione_id_fabbrica_simulazione
    usecase "UCS1.1 - Visualizzazione singolo Gateway simulato" as visualizzazione_singolo_gateway_simulato
}

SA_sym_usr -right-> visualizzazione_singolo_gateway_simulato
visualizzazione_singolo_gateway_simulato -down..> visualizzazione_data_creazione_simulazione : <<include>>
visualizzazione_singolo_gateway_simulato -down..> visualizzazione_id_fabbrica_simulazione : <<include>>
@enduml