@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS7 - Visualizzazione tipo sensore simulato" as visualizzazione_tipo_sensore_simulato
}

SA_sym_usr -right-> visualizzazione_tipo_sensore_simulato
@enduml