@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS3.2 - Visualizzazione serial number del gateway simulato" as visualizzazione_serial_number_gateway_simulato
}

SA_sym_usr -right-> visualizzazione_serial_number_gateway_simulato
@enduml