@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS1.1.1 - Visualizzazione data di creazione del Gateway Simulato" as visualizzazione_data_creazione_simulazione
}

SA_sym_usr -right-> visualizzazione_data_creazione_simulazione
@enduml