@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS6 - Visualizzazione identificativo sensore" as visualizzazione_identificativo_sensore
    usecase "UCS4.1 - Visualizzazione singolo sensore simulato" as visualizzazione_singolo_sensore_simulato
    usecase "UCS7 - Visualizzazione tipo sensore simulato" as visualizzazione_tipo_sensore_simulato
}

SA_sym_usr -right-> visualizzazione_singolo_sensore_simulato
visualizzazione_singolo_sensore_simulato -down..> visualizzazione_identificativo_sensore : <<include>>
visualizzazione_singolo_sensore_simulato -down..> visualizzazione_tipo_sensore_simulato : <<include>>
@enduml