@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS6 - Visualizzazione identificativo sensore" as visualizzazione_identificativo_sensore
}

SA_sym_usr -right-> visualizzazione_identificativo_sensore
@enduml