@startuml
skinparam wrapWidth 200
skinparam MaxMessageSize 150
top to bottom direction
skinparam packageStyle rectangle

actor "Utente del Simulatore" as SA_sym_usr

rectangle "Sistema" {
    usecase "UCS4 - Visualizzazione lista sensori Gateway simulato" as visualizzazione_lista_sensori_gateway_simulato
    usecase "UCS4.1 - Visualizzazione singolo sensore simulato" as visualizzazione_singolo_sensore_simulato
}

SA_sym_usr -right-> visualizzazione_lista_sensori_gateway_simulato
visualizzazione_lista_sensori_gateway_simulato -down..> visualizzazione_singolo_sensore_simulato : <<include>>
@enduml