name: Stability Index - Analisi Requisiti

on:
  push:
    branches:
      - main
    paths:
      - "docs/12-rtb/docest/analisi_requisiti/**"
  workflow_dispatch:

jobs:
  stability-index:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/notipswe/notip-docs-dev:v0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-docs-env

      - name: Calculate Stability Index and send to Google Sheets
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: notipdo metrics stability-index --sheet
